#!/usr/bin/env node
/* Which imported items are magical — the scan that decides it, and the table it writes.

   WHY THIS IS INCREMENTAL. The owner, 2026-09-10: "Since the items from captured or killed PCs
   should never change, can you ensure that the next snapshot only updates the table with newly
   captured or killed players? There is no sense in scanning the records again."

   He is right, and it is the whole design here. A captured or dead character is FINISHED: their
   loadout cannot change again, so a verdict about their possessions is permanent. An active
   character is still playing and still picking things up, so judging them now buys a verdict
   that may be stale next week — and only captured characters enter the Main Game anyway
   (RIDDLE_OF_STEEL §2). So the default pass considers captured and dead records only, and skips
   every (character, item) pair already recorded in magic_scan.json.

   IT CANNOT SPEND MONEY BY ACCIDENT. A bare run is a DRY RUN: it reports exactly what it would
   send and what that would cost, and exits. Spending requires --run. That is deliberate — the
   first full scan cost $3.64 and the owner tracks his credits.

     node scan_magic.mjs                      what would be scanned, and the cost. Spends nothing.
     node scan_magic.mjs --run                scan the new captured/dead items, update the table
     node scan_magic.mjs --table-only         rebuild js/data/magic_import.js from the ledger
     node scan_magic.mjs --rescan "hakim"     re-judge matching entries (character or item text)
     node scan_magic.mjs --rescan-all --run   throw the ledger away and judge everything again
     node scan_magic.mjs --include-active     also consider characters still in play
     node scan_magic.mjs --include-kit        also consider issued starting-kit items

   FILES.  magic_scan.json is the provenance record — every verdict ever reached, including the
   ordinary ones, which is what makes "already judged" answerable at all (the shipped table holds
   only the non-mundane, so it cannot serve as that record). js/data/magic_import.js is GENERATED
   from it and is what the builder loads.

   DATA.  Reads the live Two Snakes records over ssh, and runs the extraction ON the box so the
   data file — which carries the API key and player PINs — never leaves it. Only item names,
   ledger descriptions and the story passages that mention them come back. */

import { execFileSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const LEDGER = path.join(HERE, 'magic_scan.json');
const TABLE = path.join(HERE, 'js', 'data', 'magic_import.js');
const VPS = process.env.TS_VPS || 'root@172.234.254.210';
const DATA = process.env.TS_DATA || '/home/deploy/two-snakes/two_snakes_data.json';

const argv = process.argv.slice(2);
const has = f => argv.includes(f);
const val = f => { const i = argv.indexOf(f); return i >= 0 ? argv[i + 1] : null; };
const RUN = has('--run');
const TABLE_ONLY = has('--table-only');
const RESCAN_ALL = has('--rescan-all');
const RESCAN = val('--rescan');
const WITH_ACTIVE = has('--include-active');
const WITH_KIT = has('--include-kit');
const norm = s => String(s || '').toLowerCase().replace(/\s+/g, ' ').trim();
const key = (c, i) => norm(c) + '||' + norm(i);

/* ---------------------------------------------------------------- the ledger */
function readLedger() {
  try { return JSON.parse(fs.readFileSync(LEDGER, 'utf8')); }
  catch (e) { return { note: 'provenance record for scan_magic.mjs', scans: [] }; }
}

/* ---------------------------------------------------------------- the table */
function writeTable(ledger) {
  const rows = {};
  let mag = 0, unc = 0, mun = 0;
  ledger.scans.forEach(x => {
    if (x.verdict === 'mundane') { mun++; return; }
    if (x.verdict === 'magical') mag++; else unc++;
    rows[key(x.character, x.item)] = {
      v: x.verdict,
      effect: (x.effect || '').trim(),
      drawback: (x.drawback || '').trim(),
      evidence: (x.evidence || '').trim()
    };
  });
  const body = Object.keys(rows).sort()
    .map(k => '    ' + JSON.stringify(k) + ': ' + JSON.stringify(rows[k])).join(',\n');
  fs.writeFileSync(TABLE, `/* Pathfinder 1E Character Builder — which imported items are magical.

   GENERATED by scan_magic.mjs from magic_scan.json. Do not hand-edit this file; correct a
   verdict in magic_scan.json and re-run \`node scan_magic.mjs --table-only\`. The DM outranks
   both files — anything here can be moved back to gear on the sheet.

   WHY A TABLE AND NOT A PREDICATE. The first attempt matched item names and ledger prose.
   Measured against the real inventories it matched "ward" inside "rewards" and "charm" inside
   "charming", convicted a standard-issue thief's cloak because the prose said it "swallows
   light", and was blind to a "jade cylinder" carrying no description at all. The owner: "pattern
   matching against things like 'charm' or 'magic' isn't going to cut it."

   So the judgment is made by a model reading the narrative each object actually appeared in, and
   frozen here. The builder performs a LOOKUP, never a guess. An item absent from this table is
   ordinary gear; nothing is inferred from its name.

   ${mag} magical, ${unc} uncertain, ${mun} ordinary (ordinary items are not listed).
   'uncertain' means unnatural make or provenance but nothing demonstrated — it still routes to
   Magic Items, flagged for a ruling, because that is the category the owner asked to stop
   losing in the gear list. */
(function () {
  const PF = (window.PF = window.PF || {});
  const D = (PF.DATA = PF.DATA || {});

  D.IMPORT_MAGIC = {
${body}
  };
}());
`);
  return { mag, unc, mun, total: Object.keys(rows).length };
}

if (TABLE_ONLY) {
  const t = writeTable(readLedger());
  console.log(`rebuilt ${path.relative(HERE, TABLE)} — ${t.total} entries (${t.mag} magical, ${t.unc} uncertain; ${t.mun} ordinary not listed)`);
  process.exit(0);
}

/* ---------------------------------------------------------------- candidates, from the VPS */
const EXTRACT = `
const fs = require('fs');
const blob = JSON.parse(fs.readFileSync(${JSON.stringify(DATA)}, 'utf8'));
const chars = {};
Object.keys(blob).filter(k => /^ts_(char|hist):/i.test(k)).forEach(k => {
  let r; try { r = JSON.parse(blob[k]); } catch (e) { r = blob[k]; }
  if (!r || typeof r !== 'object') return;
  const cd = r.charData || {}; const nm = cd.name; if (!nm) return;
  const inv = (cd.sheet && cd.sheet.inv) || cd.inv || [];
  const log = Array.isArray(r.storyLog) ? r.storyLog : [];
  const st = String(r.status || '');
  const prev = chars[nm];
  /* keep the record with the longest log; a finished status outranks 'active' */
  if (!prev || log.length > prev.log.length) chars[nm] = { status: st, inv: inv, log: log };
  else if (prev.status === 'active' && st && st !== 'active') prev.status = st;
});
const nameCount = {};
Object.keys(chars).forEach(n => (chars[n].inv || []).forEach(it => {
  const s = String(it.name || '').toLowerCase().trim(); if (s) nameCount[s] = (nameCount[s] || 0) + 1;
}));
const STOP = new Set(['of','the','a','an','and','with','in','on','for','set','pair','small','large',
  'dark','old','new','iron','silver','gold','bronze','leather','wooden','their','his','her','3','2','1']);
const out = [];
Object.keys(chars).forEach(nm => {
  const c = chars[nm];
  (c.inv || []).forEach(it => {
    const k = String(it.name || '').toLowerCase().trim(); if (!k) return;
    const kit = nameCount[k] > 2;
    const words = String(it.name).toLowerCase().replace(/[(),.]/g, ' ').split(/\\s+/)
      .filter(w => w.length > 3 && !STOP.has(w));
    const hits = [];
    if (words.length) c.log.forEach((m, i) => {
      const t = String(m.text || '').toLowerCase();
      if (words.some(w => t.indexOf(w) >= 0)) {
        for (let j = Math.max(0, i - 1); j <= Math.min(c.log.length - 1, i + 1); j++) {
          if (!hits.includes(j)) hits.push(j);
        }
      }
    });
    out.push({ character: nm, status: c.status, item: it.name, desc: it.desc || '', kit: kit,
      context: hits.sort((a, b) => a - b).slice(0, 12)
        .map(j => (c.log[j].type === 'action' ? '> ' : '') + String(c.log[j].text || '').slice(0, 700)) });
  });
});
process.stdout.write(JSON.stringify(out));
`;

process.stderr.write('reading live records over ssh (the data file stays on the box)...\n');
/* The extractor is PIPED to the box, not interpolated into the remote command line. Passing it
   as `node -e "<script>"` sends it through the remote shell, which eats backslashes and $ — the
   first version of this tool died on exactly that. */
const raw = execFileSync('ssh', ['-o', 'ConnectTimeout=15', VPS,
  'cat > /tmp/ts_magic_extract.js && node /tmp/ts_magic_extract.js; rm -f /tmp/ts_magic_extract.js'],
  { input: EXTRACT, maxBuffer: 256 * 1024 * 1024 }).toString();
const all = JSON.parse(raw);

const ledger = RESCAN_ALL ? { note: readLedger().note, scans: [] } : readLedger();
const judged = new Set(ledger.scans.map(x => key(x.character, x.item)));

if (RESCAN) {
  const before = ledger.scans.length;
  ledger.scans = ledger.scans.filter(x =>
    !(norm(x.character) + ' ' + norm(x.item)).includes(norm(RESCAN)));
  judged.clear(); ledger.scans.forEach(x => judged.add(key(x.character, x.item)));
  console.log(`--rescan "${RESCAN}": dropped ${before - ledger.scans.length} existing verdict(s) to be judged again`);
}

const FINISHED = new Set(['captured', 'dead']);
const candidates = all.filter(p => {
  if (!WITH_ACTIVE && !FINISHED.has(p.status)) return false;
  if (!WITH_KIT && p.kit) return false;
  return !judged.has(key(p.character, p.item));
});

const skippedActive = all.filter(p => !FINISHED.has(p.status)).length;
const skippedJudged = all.filter(p => judged.has(key(p.character, p.item))).length;
const chars = [...new Set(candidates.map(c => c.character))];

console.log('');
console.log(`live inventory rows          : ${all.length}`);
console.log(`already judged (ledger)      : ${skippedJudged}`);
console.log(`skipped, character still active: ${skippedActive}${WITH_ACTIVE ? ' (included anyway: --include-active)' : ''}`);
console.log(`skipped, issued starting kit : ${all.filter(p => p.kit).length}${WITH_KIT ? ' (included anyway: --include-kit)' : ''}`);
console.log(`TO SCAN                      : ${candidates.length}${chars.length ? '  on ' + chars.length + ' character(s): ' + chars.join(', ').slice(0, 120) : ''}`);
candidates.slice(0, 20).forEach(c => console.log(`    ${c.character} — ${c.item}  [${c.status}, ${c.context.length} story hits]`));
if (candidates.length > 20) console.log(`    ... and ${candidates.length - 20} more`);

if (!candidates.length) {
  console.log('\nNothing new to judge. The table is current.');
  if (RUN) { const t = writeTable(ledger); fs.writeFileSync(LEDGER, JSON.stringify(ledger, null, 1));
    console.log(`table rewritten anyway — ${t.total} entries.`); }
  process.exit(0);
}

/* Cost, before spending any of it. Opus 5 is $5/$25 per Mtok (claude-api skill, 2026-06-24). */
const ctxChars = candidates.reduce((n, c) => n + c.context.join('\n').length + c.item.length + c.desc.length, 0);
const inTok = Math.round(ctxChars / 4) + Math.ceil(candidates.length / 12) * 700;
const outTok = candidates.length * 280;
const est = inTok / 1e6 * 5 + outTok / 1e6 * 25;
console.log(`\nestimated: ~${inTok.toLocaleString()} input + ~${outTok.toLocaleString()} output tokens  ≈ $${est.toFixed(2)}`);

if (!RUN) {
  console.log('\nDRY RUN — nothing was sent and nothing was spent.');
  console.log('Re-run with --run to actually scan.');
  process.exit(0);
}

/* ---------------------------------------------------------------- the scan */
const { default: Anthropic } = await import('@anthropic-ai/sdk');
const client = new Anthropic();

const SYSTEM = fs.readFileSync(path.join(HERE, 'scan_magic_prompt.txt'), 'utf8');
const schema = {
  type: 'object', additionalProperties: false, required: ['verdicts'],
  properties: { verdicts: { type: 'array', items: {
    type: 'object', additionalProperties: false,
    required: ['character', 'item', 'verdict', 'effect', 'drawback', 'evidence', 'reason'],
    properties: {
      character: { type: 'string' }, item: { type: 'string' },
      verdict: { type: 'string', enum: ['magical', 'uncertain', 'mundane'] },
      effect: { type: 'string' }, drawback: { type: 'string' },
      evidence: { type: 'string' }, reason: { type: 'string' }
    } } } }
};

const today = new Date().toISOString().slice(0, 10);
let inUsed = 0, outUsed = 0;
for (let i = 0; i < candidates.length; i += 12) {
  const batch = candidates.slice(i, i + 12);
  const body = batch.map((p, n) => `--- ITEM ${n + 1} ---
character: ${p.character}
item: ${p.item}
ledger description: ${p.desc || '(none recorded)'}
story passages mentioning it (lines beginning "> " are the player's own actions):
${p.context.length ? p.context.join('\n') : '(the item is never mentioned in the surviving story log)'}`).join('\n\n');

  const res = await client.messages.create({
    model: 'claude-opus-5', max_tokens: 8000,
    system: [{ type: 'text', text: SYSTEM, cache_control: { type: 'ephemeral' } }],
    output_config: { format: { type: 'json_schema', schema } },
    messages: [{ role: 'user', content:
      `Judge each item below. Return one verdict per item, in order, echoing character and item verbatim.\n\n${body}` }]
  });
  inUsed += res.usage.input_tokens + (res.usage.cache_creation_input_tokens || 0) + (res.usage.cache_read_input_tokens || 0);
  outUsed += res.usage.output_tokens;
  const txt = res.content.filter(b => b.type === 'text').map(b => b.text).join('');
  let parsed; try { parsed = JSON.parse(txt); }
  catch (e) { console.error(`  batch at ${i}: unparseable, skipped`); continue; }
  parsed.verdicts.forEach(v => {
    const src = batch.find(b => norm(b.item) === norm(v.item) && norm(b.character) === norm(v.character)) || {};
    ledger.scans.push({ character: v.character, item: v.item, status: src.status || 'unknown',
      verdict: v.verdict, effect: v.effect || '', drawback: v.drawback || '',
      evidence: v.evidence || '', scannedAt: today });
  });
  process.stderr.write(`  batch ${Math.floor(i / 12) + 1}: ${parsed.verdicts.length} verdicts\n`);
}

ledger.scannedAt = today;
fs.writeFileSync(LEDGER, JSON.stringify(ledger, null, 1));
const t = writeTable(ledger);
const spent = inUsed / 1e6 * 5 + outUsed / 1e6 * 25;
console.log(`\nledger: ${ledger.scans.length} judged items total`);
console.log(`table : ${t.total} entries (${t.mag} magical, ${t.unc} uncertain)`);
console.log(`spent : $${spent.toFixed(2)}  (${inUsed.toLocaleString()} in / ${outUsed.toLocaleString()} out)`);
